{"version":3,"sources":["../../app-src/util/ApplicationException.js"],"names":["ApplicationException","Error","constructor","msg","name","exception","isApplicationException","err","Object","getPrototypeOf","getExceptionMessage","message","console","log"],"mappings":";;;;;;AAAO,SAAMA,oBAAN,SAAmCC,KAAnC,CAAyC;AAC/CC,gBAAYC,MAAM,EAAlB,EAAsB;AACrB,WAAMA,GAAN;AACA,UAAKC,IAAL,GAAY,KAAKF,WAAL,CAAiBE,IAA7B;AACA;AAJ8C;;;;AAOhD,SAAMC,YAAYL,oBAAlB;AACO,YAASM,sBAAT,CAAgCC,GAAhC,EAAqC;AAC3C,WAAOA,eAAeF,SAAf,IAA4BG,OAAOC,cAAP,CAAsBF,GAAtB,aAAsCF,SAAzE;AACA;;;;AAEM,YAASK,mBAAT,CAA6BH,GAA7B,EAAkC;AACxC,QAAGD,uBAAuBC,GAAvB,CAAH,EAAgC;AAC/B,YAAOA,IAAII,OAAX;AACA,KAFD,MAEO;AACNC,aAAQC,GAAR,CAAYN,GAAZ;AACA,YAAO,uCAAP;AACA;AACD","file":"ApplicationException.js","sourcesContent":["export class ApplicationException extends Error {\n\tconstructor(msg = \"\") {\n\t\tsuper(msg);\n\t\tthis.name = this.constructor.name;\n\t}\n}\n\nconst exception = ApplicationException;\nexport function isApplicationException(err) {\n\treturn err instanceof exception || Object.getPrototypeOf(err) instanceof exception;\n}\n\nexport function getExceptionMessage(err) {\n\tif(isApplicationException(err))\t{\n\t\treturn err.message;\n\t} else {\n\t\tconsole.log(err);\n\t\treturn 'Não\tfoi\tpossível\trealizar\ta\toperação.';\n\t}\n}\n"]}